version: '3'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000